/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.DoctorRole;

import Business.Drug.Drug;
import Business.Drug.DrugFeedback;
import Business.Enterprise.Enterprise;
import Business.WebMedical;
import Business.UserAccount.EmployeeAccount;
import Business.UserAccount.PatientAccount;
import Business.UserAccount.UserAccount;
import Business.Util.ProjectUtil;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author nikhil
 */
public class DrugFeedBackJPanel extends javax.swing.JPanel {

    private JPanel userProcContainer;
    private Enterprise enterprise;
    private WebMedical system;
    private EmployeeAccount employeeAccount;
    private PatientAccount patientAccount;
    
    
    public DrugFeedBackJPanel(JPanel userProcContainer, Enterprise enterprise, 
            WebMedical system, UserAccount ua) {
        initComponents();
        this.userProcContainer = userProcContainer;
        this.enterprise = enterprise;
        this.system = system;
        if(ua instanceof PatientAccount){
            patientAccount = (PatientAccount)ua;
        }else{
            this.employeeAccount = (EmployeeAccount)ua;
        }
        populateDrugCombo();
        populateSeverityCombo();
    }

    private void populateSeverityCombo(){
        severityCombo.removeAllItems();
        
        severityCombo.addItem("Normal");
        severityCombo.addItem("Critical");
        severityCombo.addItem("Fatal");
    }
    
    private void populateDrugCombo(){
        drugCombo.removeAllItems();
        
        for(Drug drug: system.getNetwork(enterprise.getNetName()).getNationalDrugDirectory().getDrugList()){
            drugCombo.addItem(drug);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtAdverseEvent = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtEventDesc = new javax.swing.JTextArea();
        drugCombo = new javax.swing.JComboBox();
        drugFeedback = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        severityCombo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(33, 33, 33));
        setForeground(java.awt.Color.white);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Detail Event Description");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Drug");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Drug Feedback");
        jLabel1.setAutoscrolls(true);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setText("Adverse Event");

        txtAdverseEvent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtEventDesc.setColumns(20);
        txtEventDesc.setRows(5);
        jScrollPane1.setViewportView(txtEventDesc);

        drugCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        drugFeedback.setBackground(new java.awt.Color(0, 150, 136));
        drugFeedback.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        drugFeedback.setForeground(java.awt.Color.white);
        drugFeedback.setText("Record Drug Feedback");
        drugFeedback.setBorder(null);
        drugFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugFeedbackActionPerformed(evt);
            }
        });

        backJButton.setBackground(new java.awt.Color(244, 67, 57));
        backJButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        backJButton.setForeground(java.awt.Color.black);
        backJButton.setText("Back");
        backJButton.setBorder(null);
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        severityCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Severity");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAdverseEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(drugCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(130, 130, 130)))
                                .addGap(0, 0, 0)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                    .addComponent(severityCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(drugFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drugCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAdverseEvent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(severityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drugFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void drugFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugFeedbackActionPerformed
        if(drugCombo.getSelectedItem() != null){
            Drug drug = (Drug)drugCombo.getSelectedItem();
            
            String adverseEvent = txtAdverseEvent.getText();
            String desc = txtEventDesc.getText();
            
            if(ProjectUtil.isFeildEmpty(adverseEvent) ||
                    ProjectUtil.isFeildEmpty(desc)){
                JOptionPane.showMessageDialog(null, "Please fill the details");
                return;
            }
            
            if(severityCombo.getSelectedItem() == null){
                JOptionPane.showMessageDialog(null, "Select adverse event severity");
                return;
            }
            
            DrugFeedback drugFeedBack = new DrugFeedback();
            
            String personRole;
            String feedBackProvider;
            
            if(employeeAccount != null){
                personRole = "Doctor";
                feedBackProvider = employeeAccount.getEmployee().getEmpName();
            }else{
                personRole = "Patient";
                feedBackProvider = patientAccount.getPatientAccount().getFullName();
            }
            
            drugFeedBack.setAdvEvent(adverseEvent);
            drugFeedBack.setEventDescription(desc);
            drugFeedBack.setFeedbackProvider(feedBackProvider);
            drugFeedBack.setPersonRole(personRole);
            drugFeedBack.setState(enterprise.getNetState());
            drugFeedBack.setSeverity((String)severityCombo.getSelectedItem());
            
            if(drugFeedBack.getSeverity().equals("Fatal")){
                drug.incrementFatalAdverseEventCount();
            }
            
            drug.getDrugFeedbacks().add(drugFeedBack);
            
            JOptionPane.showMessageDialog(null, "Drug Feedback recorded successfully !!");
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select a drug");
        }
    }//GEN-LAST:event_drugFeedbackActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcContainer.remove(this);
        CardLayout layout = (CardLayout)userProcContainer.getLayout();
        layout.previous(userProcContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox drugCombo;
    private javax.swing.JButton drugFeedback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox severityCombo;
    private javax.swing.JTextField txtAdverseEvent;
    private javax.swing.JTextArea txtEventDesc;
    // End of variables declaration//GEN-END:variables
}
