/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorRole;

import Business.Patient.VitalSign;
import java.awt.CardLayout;
import java.sql.Timestamp;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author nikhil
 */
public class UpdateVitalSignJPanel extends javax.swing.JPanel {

    private JPanel userProcContainer;
    private VitalSign vitalSign;
    private int patientAge;

    public UpdateVitalSignJPanel(JPanel userProcContainer,
            VitalSign vitalSign, int patientAge) {
        initComponents();
        this.userProcContainer = userProcContainer;
        this.vitalSign = vitalSign;
        this.patientAge = patientAge;
        viewSelectedVitalSign();
    }

    private void viewSelectedVitalSign() {
        rspRateJTextField.setText(String.valueOf(vitalSign.getRespRate()));
        heartRateJTextField.setText(String.valueOf(vitalSign.getHeartRate()));
        systBlPreJTextField.setText(String.valueOf(vitalSign.getBloodPressure()));
        weightJTextField.setText(String.valueOf(vitalSign.getWieghtInPounds()));
        timestampJTextField.setText(String.valueOf(vitalSign.getTimestamp()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        respRateJLabel = new javax.swing.JLabel();
        rspRateJTextField = new javax.swing.JTextField();
        weightJLabel = new javax.swing.JLabel();
        timestampJLabel = new javax.swing.JLabel();
        timestampJTextField = new javax.swing.JTextField();
        systBlPreJLabel = new javax.swing.JLabel();
        updateVitalSignJButton = new javax.swing.JButton();
        weightJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        heartRateJTextField = new javax.swing.JTextField();
        heartRateJLabel = new javax.swing.JLabel();
        systBlPreJTextField = new javax.swing.JTextField();
        updateVitalSignJButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(33, 33, 33));
        setForeground(java.awt.Color.white);
        setPreferredSize(new java.awt.Dimension(500, 400));

        respRateJLabel.setForeground(java.awt.Color.white);
        respRateJLabel.setText("Respiratory Rate");

        rspRateJTextField.setForeground(java.awt.Color.white);
        rspRateJTextField.setEnabled(false);
        rspRateJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rspRateJTextFieldActionPerformed(evt);
            }
        });

        weightJLabel.setForeground(java.awt.Color.white);
        weightJLabel.setText("Weight in Pounds");

        timestampJLabel.setForeground(java.awt.Color.white);
        timestampJLabel.setText("Timestamp");

        timestampJTextField.setForeground(java.awt.Color.white);
        timestampJTextField.setEnabled(false);
        timestampJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timestampJTextFieldActionPerformed(evt);
            }
        });

        systBlPreJLabel.setForeground(java.awt.Color.white);
        systBlPreJLabel.setText("Systolic Blood Pressure");

        updateVitalSignJButton.setBackground(new java.awt.Color(255, 193, 7));
        updateVitalSignJButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        updateVitalSignJButton.setForeground(java.awt.Color.black);
        updateVitalSignJButton.setText("Update");
        updateVitalSignJButton.setBorder(null);
        updateVitalSignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateVitalSignJButtonActionPerformed(evt);
            }
        });

        weightJTextField.setForeground(java.awt.Color.white);
        weightJTextField.setEnabled(false);
        weightJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightJTextFieldActionPerformed(evt);
            }
        });

        backJButton.setBackground(new java.awt.Color(244, 67, 54));
        backJButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        backJButton.setForeground(java.awt.Color.black);
        backJButton.setText("Back");
        backJButton.setBorder(null);
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        heartRateJTextField.setForeground(java.awt.Color.white);
        heartRateJTextField.setEnabled(false);
        heartRateJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heartRateJTextFieldActionPerformed(evt);
            }
        });

        heartRateJLabel.setForeground(java.awt.Color.white);
        heartRateJLabel.setText("Heart Rate");

        systBlPreJTextField.setForeground(java.awt.Color.white);
        systBlPreJTextField.setEnabled(false);
        systBlPreJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                systBlPreJTextFieldActionPerformed(evt);
            }
        });

        updateVitalSignJButton1.setBackground(new java.awt.Color(0, 150, 136));
        updateVitalSignJButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        updateVitalSignJButton1.setForeground(java.awt.Color.white);
        updateVitalSignJButton1.setText("Save");
        updateVitalSignJButton1.setBorder(null);
        updateVitalSignJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateVitalSignJButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(weightJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(weightJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(systBlPreJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(systBlPreJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(heartRateJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(heartRateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(respRateJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rspRateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(timestampJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(timestampJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(updateVitalSignJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(updateVitalSignJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rspRateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(respRateJLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(heartRateJLabel)
                    .addComponent(heartRateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(systBlPreJLabel)
                    .addComponent(systBlPreJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weightJLabel)
                    .addComponent(weightJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timestampJLabel)
                    .addComponent(timestampJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateVitalSignJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateVitalSignJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rspRateJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rspRateJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rspRateJTextFieldActionPerformed

    private void timestampJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timestampJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timestampJTextFieldActionPerformed

    private void updateVitalSignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateVitalSignJButtonActionPerformed
        rspRateJTextField.setEnabled(true);
        heartRateJTextField.setEnabled(true);
        systBlPreJTextField.setEnabled(true);
        weightJTextField.setEnabled(true);
        JOptionPane.showMessageDialog(null, "Vital Sign Updated");
    }//GEN-LAST:event_updateVitalSignJButtonActionPerformed

    private void weightJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightJTextFieldActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcContainer.remove(this);

        CardLayout layout = (CardLayout) userProcContainer.getLayout();
        layout.previous(userProcContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void clearVitalSignTextFields() {
        rspRateJTextField.setText("");
        heartRateJTextField.setText("");
        systBlPreJTextField.setText("");
        weightJTextField.setText("");
        timestampJTextField.setText("");
    }

    private void heartRateJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heartRateJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heartRateJTextFieldActionPerformed

    private void systBlPreJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_systBlPreJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_systBlPreJTextFieldActionPerformed

    private void updateVitalSignJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateVitalSignJButton1ActionPerformed
        int respiratoryRate;
        int heartRate;
        int systolicBloodPressure;
        int weight;
        String timestamp;

        try {
            respiratoryRate = Integer.parseInt(rspRateJTextField.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Respiratory value should be Numeric Integer!!");
            return;
        }

        try {
            heartRate = Integer.parseInt(heartRateJTextField.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Heart Rate value should be Numeric Integer!!");
            return;
        }

        try {
            systolicBloodPressure = Integer.parseInt(systBlPreJTextField.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Systolic Blood Pressure value should be Numeric Integer!!");
            return;
        }

        try {
            weight = Integer.parseInt(weightJTextField.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Weight of the patient should be Numeric Integer!!");
            return;
        }

        timestamp = getCurrentTimestamp();
        vitalSign.setRespRate(respiratoryRate);
        vitalSign.setHeartRate(heartRate);
        vitalSign.setBloodPressure(systolicBloodPressure);
        vitalSign.setWieghtInPounds(weight);
        vitalSign.setTimestamp(timestamp);
        vitalSign.setVitalSignStatus(vitalSign.evaluateVitalSignStatus(patientAge));

        rspRateJTextField.setEnabled(false);
        heartRateJTextField.setEnabled(false);
        systBlPreJTextField.setEnabled(false);
        weightJTextField.setEnabled(false);
    }//GEN-LAST:event_updateVitalSignJButton1ActionPerformed

    private String getCurrentTimestamp() {
        Calendar calender = Calendar.getInstance();
        Date date = calender.getTime();
        Timestamp timestamp = new Timestamp(date.getTime());
        return timestamp.toString();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel heartRateJLabel;
    private javax.swing.JTextField heartRateJTextField;
    private javax.swing.JLabel respRateJLabel;
    private javax.swing.JTextField rspRateJTextField;
    private javax.swing.JLabel systBlPreJLabel;
    private javax.swing.JTextField systBlPreJTextField;
    private javax.swing.JLabel timestampJLabel;
    private javax.swing.JTextField timestampJTextField;
    private javax.swing.JButton updateVitalSignJButton;
    private javax.swing.JButton updateVitalSignJButton1;
    private javax.swing.JLabel weightJLabel;
    private javax.swing.JTextField weightJTextField;
    // End of variables declaration//GEN-END:variables
}
