/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.DoctorRole;

import Business.FileUtil.BaseViewer;
import Business.WebMedical;
import Business.Patient.Allergy;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nikhil
 */
public class ViewPatientClinicalInfoJPanel extends javax.swing.JPanel {

    JPanel userProcContainer;
    Patient patient;
    UserAccount ua;
    
    public ViewPatientClinicalInfoJPanel(JPanel userProcContainer, UserAccount ua, Patient patient) {
        initComponents();
        this.userProcContainer = userProcContainer;
        this.patient = patient;
        this.ua = ua;
        populateAllergyTable();
        populateMedicationTable();
        populateTestResultsTable();
    }

    private void populateAllergyTable(){
        DefaultTableModel model = (DefaultTableModel) alleryTable.getModel();

        model.setRowCount(0);
        for (Allergy allergy: patient.getAllergyInformation().getAllergyList()) {
                Object[] row = new Object[2];
                row[0] = allergy.getAllergyType();
                row[1] = allergy.getDescription();
                
                model.addRow(row);
            }
    }
    
    private void populateMedicationTable(){
        DefaultTableModel model = (DefaultTableModel) medicationTable.getModel();

        model.setRowCount(0);
        for (String medication: patient.getPatientMedications()) {
                Object[] row = new Object[1];
                row[0] = medication;
                
                model.addRow(row);
            }
    }
    
    private void populateTestResultsTable(){
        DefaultTableModel model = (DefaultTableModel) testResultsTable.getModel();

        model.setRowCount(0);
        for (String labTestResult: patient.getLabTestHistory()) {
                Object[] row = new Object[1];
                row[0] = labTestResult;
                
                model.addRow(row);
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alleryTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        medicationTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        testResultsTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        viewMedication = new javax.swing.JButton();
        viewTestReport = new javax.swing.JButton();
        nextJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(33, 33, 33));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Clinical Information");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Allergy Information");

        jScrollPane1.setForeground(java.awt.Color.white);

        alleryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Allergy Type", "Description"
            }
        ));
        jScrollPane1.setViewportView(alleryTable);

        jScrollPane2.setForeground(java.awt.Color.white);

        medicationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medication"
            }
        ));
        jScrollPane2.setViewportView(medicationTable);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Patient Medications");

        jScrollPane3.setForeground(java.awt.Color.white);

        testResultsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Test Reports"
            }
        ));
        jScrollPane3.setViewportView(testResultsTable);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Patient Test Reports");

        viewMedication.setBackground(new java.awt.Color(255, 193, 7));
        viewMedication.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        viewMedication.setForeground(java.awt.Color.black);
        viewMedication.setText("View");
        viewMedication.setBorder(null);
        viewMedication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMedicationActionPerformed(evt);
            }
        });

        viewTestReport.setBackground(new java.awt.Color(255, 193, 7));
        viewTestReport.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        viewTestReport.setForeground(java.awt.Color.black);
        viewTestReport.setText("View");
        viewTestReport.setBorder(null);
        viewTestReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTestReportActionPerformed(evt);
            }
        });

        nextJButton.setBackground(new java.awt.Color(0, 150, 136));
        nextJButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nextJButton.setForeground(java.awt.Color.white);
        nextJButton.setText("Next");
        nextJButton.setBorder(null);
        nextJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextJButtonActionPerformed(evt);
            }
        });

        backJButton.setBackground(new java.awt.Color(244, 67, 54));
        backJButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        backJButton.setForeground(java.awt.Color.black);
        backJButton.setText("Back");
        backJButton.setBorder(null);
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nextJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(viewMedication, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                .addComponent(viewTestReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(60, 60, 60))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(viewMedication, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(viewTestReport, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nextJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextJButtonActionPerformed
        CardLayout layout = (CardLayout) userProcContainer.getLayout();
        userProcContainer.add("ViewVitalSignJPanel", new ViewVitalSignJPanel(userProcContainer,ua, patient));
        layout.next(userProcContainer);
    }//GEN-LAST:event_nextJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcContainer.remove(this);
        CardLayout layout = (CardLayout)userProcContainer.getLayout();
        layout.previous(userProcContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void viewMedicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMedicationActionPerformed
        int row = medicationTable.getSelectedRow();

        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }
        
        String medication = (String)medicationTable.getValueAt(row, 0);
        
        String fileLocation = WebMedical.getServerFileLocation() 
                + "\\" + patient.getPatientId() + "\\" + "Medications" + "\\" + medication;
        
        BaseViewer view = new BaseViewer();
        view.viewPdfFile(fileLocation);
    }//GEN-LAST:event_viewMedicationActionPerformed

    private void viewTestReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTestReportActionPerformed
         int row = testResultsTable.getSelectedRow();

        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }
        
        String testResult = (String)testResultsTable.getValueAt(row, 0);
        
        String fileLocation = WebMedical.getServerFileLocation() 
                + "\\" + patient.getPatientId() + "\\" + "Tests" + "\\" + testResult;
        
        BaseViewer view = new BaseViewer();
        view.viewPdfFile(fileLocation);
    }//GEN-LAST:event_viewTestReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable alleryTable;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable medicationTable;
    private javax.swing.JButton nextJButton;
    private javax.swing.JTable testResultsTable;
    private javax.swing.JButton viewMedication;
    private javax.swing.JButton viewTestReport;
    // End of variables declaration//GEN-END:variables
}
