/*
 * EnterpriseAdminWorkAreaJPanel.java
 *
 * Created on October 10, 2008, 8:50 AM
 */

package UserInterface.EnterpriseAdminRole;

import Business.Enterprise.Enterprise;
import Business.WebMedical;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author  nikhil
 */
public class EnterpriseAdminWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    WebMedical system;
    UserAccount ua;
    /** Creates new form AdminWorkAreaJPanel
     * @param userProcessContainer
     * @param enterprise
     * @param ua
     * @param system */
    public EnterpriseAdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, 
            WebMedical system, UserAccount ua) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.ua = ua;
        this.system = system;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        userJButton = new javax.swing.JButton();
        manageEmployeeJButton = new javax.swing.JButton();
        manageOrganizationJButton = new javax.swing.JButton();
        addPatientJButton = new javax.swing.JButton();
        incomingNetworkInfoRequets = new javax.swing.JButton();
        outgoingNetworkInfoRequets = new javax.swing.JButton();

        setBackground(new java.awt.Color(33, 33, 33));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("My Work Area -Aminstrative Role");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        userJButton.setBackground(new java.awt.Color(211, 47, 47));
        userJButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        userJButton.setForeground(java.awt.Color.black);
        userJButton.setText("Manage User");
        userJButton.setBorder(null);
        userJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userJButtonActionPerformed(evt);
            }
        });
        add(userJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 460, 60));

        manageEmployeeJButton.setBackground(new java.awt.Color(255, 167, 51));
        manageEmployeeJButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        manageEmployeeJButton.setForeground(java.awt.Color.black);
        manageEmployeeJButton.setText("Manage Employee");
        manageEmployeeJButton.setBorder(null);
        manageEmployeeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeeJButtonActionPerformed(evt);
            }
        });
        add(manageEmployeeJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 460, 60));

        manageOrganizationJButton.setBackground(new java.awt.Color(0, 150, 136));
        manageOrganizationJButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        manageOrganizationJButton.setForeground(java.awt.Color.black);
        manageOrganizationJButton.setText("Manage Organization");
        manageOrganizationJButton.setBorder(null);
        manageOrganizationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationJButtonActionPerformed(evt);
            }
        });
        add(manageOrganizationJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 460, 60));

        addPatientJButton.setBackground(new java.awt.Color(0, 150, 136));
        addPatientJButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        addPatientJButton.setForeground(java.awt.Color.black);
        addPatientJButton.setText("Add Patient to System Requests");
        addPatientJButton.setBorder(null);
        addPatientJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatientJButtonActionPerformed(evt);
            }
        });
        add(addPatientJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 460, 60));

        incomingNetworkInfoRequets.setBackground(new java.awt.Color(211, 47, 47));
        incomingNetworkInfoRequets.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        incomingNetworkInfoRequets.setForeground(java.awt.Color.black);
        incomingNetworkInfoRequets.setText("Incoming Patient Info Requests Over Network ");
        incomingNetworkInfoRequets.setBorder(null);
        incomingNetworkInfoRequets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incomingNetworkInfoRequetsActionPerformed(evt);
            }
        });
        add(incomingNetworkInfoRequets, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 530, 460, 60));

        outgoingNetworkInfoRequets.setBackground(new java.awt.Color(255, 167, 51));
        outgoingNetworkInfoRequets.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        outgoingNetworkInfoRequets.setForeground(java.awt.Color.black);
        outgoingNetworkInfoRequets.setText("Outgoing  Patient Info Requests Over Network ");
        outgoingNetworkInfoRequets.setBorder(null);
        outgoingNetworkInfoRequets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outgoingNetworkInfoRequetsActionPerformed(evt);
            }
        });
        add(outgoingNetworkInfoRequets, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 460, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void userJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userJButtonActionPerformed
        // TODO add your handling code here:
        ManageUserAccountJPanel muajp = new ManageUserAccountJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("ManageUserAccountJPanel", muajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_userJButtonActionPerformed

    private void manageEmployeeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeeJButtonActionPerformed

        ManageEmployeeJPanel manageEmployeeJPanel = new ManageEmployeeJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("manageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_manageEmployeeJButtonActionPerformed

    private void manageOrganizationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationJButtonActionPerformed

        ManageOrganizationJPanel manageOrganizationJPanel = new ManageOrganizationJPanel(userProcessContainer, enterprise.getOrganizationDirectory(), 
                enterprise.getEntType());
        userProcessContainer.add("manageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrganizationJButtonActionPerformed

    private void addPatientJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatientJButtonActionPerformed
        AddPatientToSystemJPanel addPatientToSysJPanel = new AddPatientToSystemJPanel(userProcessContainer, 
        system, ua);
        userProcessContainer.add("addPatientToSysJPanel", addPatientToSysJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addPatientJButtonActionPerformed

    private void incomingNetworkInfoRequetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incomingNetworkInfoRequetsActionPerformed
        IncomingPatientInfoRequestJPanel incomingRequests = new IncomingPatientInfoRequestJPanel(userProcessContainer, 
         ua, enterprise);
        userProcessContainer.add("IncomingPatientInfoRequestJPanel", incomingRequests);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_incomingNetworkInfoRequetsActionPerformed

    private void outgoingNetworkInfoRequetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outgoingNetworkInfoRequetsActionPerformed
        OutgoingPatientInfoRequestJPanel outgoingRequests = new OutgoingPatientInfoRequestJPanel(userProcessContainer, 
        system, ua);
        userProcessContainer.add("OutgoingPatientInfoRequestJPanel", outgoingRequests);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_outgoingNetworkInfoRequetsActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPatientJButton;
    private javax.swing.JButton incomingNetworkInfoRequets;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageEmployeeJButton;
    private javax.swing.JButton manageOrganizationJButton;
    private javax.swing.JButton outgoingNetworkInfoRequets;
    private javax.swing.JButton userJButton;
    // End of variables declaration//GEN-END:variables
    
}
