/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminWorkArea;

import Business.WebMedical;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Util.ProjectUtil;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shail
 */
public class ManageEnterpriseJPanel extends javax.swing.JPanel {

    private JPanel upc;
    private WebMedical webMedical;

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    public ManageEnterpriseJPanel(JPanel userProcessContainer, WebMedical system) {
        initComponents();
        this.upc = userProcessContainer;
        this.webMedical = system;

        populateTable();
        populateComboBox();
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) enterpriseJTable.getModel();

        model.setRowCount(0);
        for (Network network : webMedical.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                Object[] row = new Object[4];
                row[0] = enterprise;
                row[1] = enterprise.getEntType().getValue();
                row[2] = network.getCountryName();
                row[3] = enterprise.getNetState();

                model.addRow(row);
            }
        }
    }

    private void populateComboBox() {
        networkCombo.removeAllItems();
        enterpriseTypeCombo.removeAllItems();

        for (Network network : webMedical.getNetworkList()) {
            networkCombo.addItem(network);
        }

        for (Enterprise.EnterpriseType type : Enterprise.EnterpriseType.values()) {
            enterpriseTypeCombo.addItem(type);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        enterpriseJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        networkCombo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        enterpriseTypeCombo = new javax.swing.JComboBox();
        submitJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        refreshJButton = new javax.swing.JButton();
        stateCombo = new javax.swing.JComboBox();
        deleteButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(33, 33, 33));
        setLayout(null);

        enterpriseJTable.setBackground(new java.awt.Color(102, 102, 102));
        enterpriseJTable.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        enterpriseJTable.setForeground(new java.awt.Color(255, 255, 255));
        enterpriseJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise Name", "Type", "Network", "State"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(enterpriseJTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(70, 70, 523, 95);

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Network Name");
        add(jLabel1);
        jLabel1.setBounds(118, 260, 130, 21);

        networkCombo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        networkCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        networkCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkComboActionPerformed(evt);
            }
        });
        add(networkCombo);
        networkCombo.setBounds(300, 260, 136, 25);

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Assign Name");
        add(jLabel2);
        jLabel2.setBounds(118, 389, 160, 21);

        nameTxt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        add(nameTxt);
        nameTxt.setBounds(300, 390, 136, 25);

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enterprise Type");
        add(jLabel3);
        jLabel3.setBounds(118, 303, 160, 21);

        enterpriseTypeCombo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        enterpriseTypeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        enterpriseTypeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseTypeComboActionPerformed(evt);
            }
        });
        add(enterpriseTypeCombo);
        enterpriseTypeCombo.setBounds(300, 300, 136, 25);

        submitJButton.setBackground(new java.awt.Color(51, 51, 51));
        submitJButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        submitJButton.setForeground(new java.awt.Color(255, 255, 255));
        submitJButton.setText("Submit");
        submitJButton.setBorder(null);
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton);
        submitJButton.setBounds(340, 450, 100, 42);

        backJButton.setBackground(new java.awt.Color(51, 51, 51));
        backJButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("Back");
        backJButton.setBorder(null);
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton);
        backJButton.setBounds(80, 450, 78, 42);

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("State Name");
        add(jLabel4);
        jLabel4.setBounds(118, 346, 110, 21);

        refreshJButton.setBackground(new java.awt.Color(51, 51, 51));
        refreshJButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        refreshJButton.setForeground(new java.awt.Color(255, 255, 255));
        refreshJButton.setText("Refresh");
        refreshJButton.setBorder(null);
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        add(refreshJButton);
        refreshJButton.setBounds(70, 190, 105, 42);

        stateCombo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        stateCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        stateCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateComboActionPerformed(evt);
            }
        });
        add(stateCombo);
        stateCombo.setBounds(300, 350, 136, 25);

        deleteButton.setBackground(new java.awt.Color(51, 51, 51));
        deleteButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("Delete");
        deleteButton.setBorder(null);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        add(deleteButton);
        deleteButton.setBounds(510, 190, 88, 42);

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("MANAGE ENTERPRISE");
        add(jLabel6);
        jLabel6.setBounds(260, 10, 430, 49);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\shail\\OneDrive\\Desktop\\finalProject indivifual\\ENTE.png")); // NOI18N
        add(jLabel7);
        jLabel7.setBounds(290, 10, 760, 700);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\shail\\OneDrive\\Desktop\\finalProject indivifual\\grad 123.jpg")); // NOI18N
        jLabel5.setText("jLabel5");
        add(jLabel5);
        jLabel5.setBounds(0, 0, 1140, 690);
    }// </editor-fold>//GEN-END:initComponents

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed

        Network network = (Network) networkCombo.getSelectedItem();
        Enterprise.EnterpriseType type = (Enterprise.EnterpriseType) enterpriseTypeCombo.getSelectedItem();

        if (network == null || type == null) {
            JOptionPane.showMessageDialog(null, "Invalid Input for network!");
            return;
        }

        String name = nameTxt.getText();

        if (ProjectUtil.isFeildEmpty(name)) {
            JOptionPane.showMessageDialog(null, "Enter valid enterprise name");
            return;
        }

        if (type.equals(Enterprise.EnterpriseType.FDA)) {
            if (!network.getEnterpriseDirectory().isFDAEnterpriseExists()) {
                Enterprise enterprise = network.getEnterpriseDirectory().createAndAddEnterprise(
                        name, type, null);
                enterprise.setNetName(network.getCountryName());
                JOptionPane.showMessageDialog(null, "FDA Enterprise created successfully");
            } else {
                JOptionPane.showMessageDialog(null, "FDA enterprise for the network : " + network.getCountryName()
                        + " alreay exists!");
            }
            return;
        }
        
        String state = (String)stateCombo.getSelectedItem();
        if (ProjectUtil.isFeildEmpty(state)) {
            JOptionPane.showMessageDialog(null, "Select a  valid state for the enterprise");
            return;
        }

        Enterprise enterprise = network.getEnterpriseDirectory().createAndAddEnterprise(name, type, state);
        enterprise.setNetName(network.getCountryName());

        JOptionPane.showMessageDialog(null, "Enterprise successfully created");
        
        populateTable();

    }//GEN-LAST:event_submitJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        upc.remove(this);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.previous(upc);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        populateTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void enterpriseTypeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseTypeComboActionPerformed

        if (enterpriseTypeCombo.getSelectedItem() != null) {
            Enterprise.EnterpriseType enterpriseType = (Enterprise.EnterpriseType) 
                    enterpriseTypeCombo.getSelectedItem();

            if (enterpriseType.equals(Enterprise.EnterpriseType.FDA)) {
                stateCombo.setEnabled(false);
            }else{
                stateCombo.setEnabled(true);
            }
        }
    }//GEN-LAST:event_enterpriseTypeComboActionPerformed

    private void networkComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkComboActionPerformed
        if(networkCombo.getSelectedItem() == null){
            return;
        }
        
        String network = ((Network)networkCombo.getSelectedItem()).getCountryName();
        
        populateStateCombo(network);
    }//GEN-LAST:event_networkComboActionPerformed

    private void populateStateCombo(String network){
        stateCombo.removeAllItems();
        switch (network) {
            case "INDIA":
                stateCombo.addItem("Maharashtra");
                stateCombo.addItem("Delhi");
                stateCombo.addItem("Tamil Nadu");
                break;
            case "USA":
                stateCombo.addItem("Massechusets");
                stateCombo.addItem("New Jersey");
                stateCombo.addItem("Illinois");
                break;
            
            case "CHINA":
                stateCombo.addItem("Shanghai");
                stateCombo.addItem("Fujian");
                stateCombo.addItem("Tibet");
                break;
        }
    }
    
    private void stateComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateComboActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int row = enterpriseJTable.getSelectedRow();

        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a specific row");
            return;
        }
        
        Enterprise enterprise = (Enterprise) enterpriseJTable.getValueAt(row, 0);
        
        webMedical.getNetwork(enterprise.getNetName()).getEnterpriseDirectory().deleteEnterprise(enterprise);
        
        JOptionPane.showMessageDialog(null, "Enterprise successfully deleted");
    }//GEN-LAST:event_deleteButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTable enterpriseJTable;
    private javax.swing.JComboBox enterpriseTypeCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JComboBox networkCombo;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JComboBox stateCombo;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
