
package UserInterface.SystemAdminWorkArea;

import Business.WebMedical;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Role.AdminRole;
import Business.Role.MedsProductionRole;
import Business.Role.DrugAdminRole;
import Business.UserAccount.UserAccount;
import Business.Util.ProjectUtil;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shail
 */
public class ManageEnterpriseAdminJPanel extends javax.swing.JPanel {

    private JPanel upc;
    private WebMedical webMedical;

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    public ManageEnterpriseAdminJPanel(JPanel userProcessContainer, WebMedical webMedical) {
        initComponents();

        this.upc = userProcessContainer;
        this.webMedical = webMedical;

        populateTable();
        populateNetworkComboBox();
    }

    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) enterpriseTbl.getModel();

        dtm.setRowCount(0);
        for (Network network : webMedical.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (UserAccount userAccount : enterprise.getUserAccountDirectory().getUserAccountList()) {
                    Object[] row = new Object[4];
                    row[0] = enterprise;
                    row[1] = network.getCountryName();
                    row[2] = enterprise.getNetState();
                    row[3] = userAccount;

                    dtm.addRow(row);
                }
            }
        }
    }

    private void populateNetworkComboBox() {
        networkComboBox.removeAllItems();

        for (Network network : webMedical.getNetworkList()) {
            networkComboBox.addItem(network);
        }
    }

    private void populateEnterpriseComboBox(Network network) {
        enterpriseComboBox.removeAllItems();

        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            enterpriseComboBox.addItem(enterprise);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        enterpriseTbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        networkComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        usernameTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        enterpriseComboBox = new javax.swing.JComboBox();
        submitJButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pwdPasswordField = new javax.swing.JPasswordField();
        backBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        enterpriseTypeTxt = new javax.swing.JTextField();
        deleteBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        setBackground(new java.awt.Color(204, 204, 204));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(600, 515));
        setLayout(null);

        enterpriseTbl.setBackground(new java.awt.Color(102, 102, 102));
        enterpriseTbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        enterpriseTbl.setForeground(new java.awt.Color(255, 255, 255));
        enterpriseTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise Name", "Network Name", "State", "Username"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(enterpriseTbl);

        add(jScrollPane1);
        jScrollPane1.setBounds(40, 130, 523, 95);

        jLabel1.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Network");
        add(jLabel1);
        jLabel1.setBounds(60, 262, 129, 21);

        networkComboBox.setBackground(new java.awt.Color(102, 102, 102));
        networkComboBox.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        networkComboBox.setForeground(new java.awt.Color(255, 255, 255));
        networkComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        networkComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkComboBoxActionPerformed(evt);
            }
        });
        add(networkComboBox);
        networkComboBox.setBounds(300, 261, 136, 30);

        jLabel2.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        add(jLabel2);
        jLabel2.setBounds(60, 449, 132, 21);

        usernameTxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        add(usernameTxt);
        usernameTxt.setBounds(300, 448, 136, 30);

        jLabel3.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enterprise");
        add(jLabel3);
        jLabel3.setBounds(60, 325, 214, 21);

        enterpriseComboBox.setBackground(new java.awt.Color(102, 102, 102));
        enterpriseComboBox.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        enterpriseComboBox.setForeground(new java.awt.Color(255, 255, 255));
        enterpriseComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        enterpriseComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseComboBoxActionPerformed(evt);
            }
        });
        add(enterpriseComboBox);
        enterpriseComboBox.setBounds(300, 324, 136, 30);

        submitJButton.setBackground(new java.awt.Color(51, 51, 51));
        submitJButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        submitJButton.setForeground(new java.awt.Color(255, 255, 255));
        submitJButton.setText("Submit");
        submitJButton.setBorder(null);
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton);
        submitJButton.setBounds(481, 641, 102, 42);

        jLabel4.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");
        add(jLabel4);
        jLabel4.setBounds(60, 510, 107, 21);

        nameTxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        add(nameTxt);
        nameTxt.setBounds(300, 570, 136, 30);

        jLabel5.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Name");
        add(jLabel5);
        jLabel5.setBounds(60, 571, 107, 21);

        pwdPasswordField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        add(pwdPasswordField);
        pwdPasswordField.setBounds(300, 509, 136, 30);

        backBtn.setBackground(new java.awt.Color(51, 51, 51));
        backBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Back");
        backBtn.setBorder(null);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn);
        backBtn.setBounds(60, 641, 80, 42);

        jLabel6.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Enterprise Type");
        add(jLabel6);
        jLabel6.setBounds(60, 388, 157, 21);

        enterpriseTypeTxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        enterpriseTypeTxt.setEnabled(false);
        enterpriseTypeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseTypeTxtActionPerformed(evt);
            }
        });
        add(enterpriseTypeTxt);
        enterpriseTypeTxt.setBounds(300, 387, 136, 30);

        deleteBtn.setBackground(new java.awt.Color(51, 51, 51));
        deleteBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Delete User");
        deleteBtn.setBorder(null);
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        add(deleteBtn);
        deleteBtn.setBounds(600, 170, 120, 30);

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("MANAGE ENTERPRISE ADMIN");
        add(jLabel7);
        jLabel7.setBounds(220, 80, 560, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\shail\\OneDrive\\Desktop\\finalProject indivifual\\admin system.png")); // NOI18N
        add(jLabel10);
        jLabel10.setBounds(550, 230, 450, 400);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/SystemAdminWorkArea/grad 123.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        jLabel9.setMaximumSize(new java.awt.Dimension(626, 417));
        jLabel9.setMinimumSize(new java.awt.Dimension(626, 417));
        jLabel9.setPreferredSize(new java.awt.Dimension(626, 417));
        add(jLabel9);
        jLabel9.setBounds(0, -60, 1090, 840);
    }// </editor-fold>//GEN-END:initComponents

    private void networkComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkComboBoxActionPerformed

        Network networkName = (Network) networkComboBox.getSelectedItem();
       
        if (networkName != null) {
            populateEnterpriseComboBox(networkName);
        }


    }//GEN-LAST:event_networkComboBoxActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed

        Enterprise enterpriseName = (Enterprise) enterpriseComboBox.getSelectedItem();
        String username = usernameTxt.getText();
        String password = String.valueOf(pwdPasswordField.getPassword());
        String name = nameTxt.getText();

        if (ProjectUtil.isFeildEmpty(username) || ProjectUtil.isFeildEmpty(password)
                || ProjectUtil.isFeildEmpty(name)) {
            JOptionPane.showMessageDialog(null, "Please enter a valid userName, password and name for"
                    + " the enterprise admin");
            return;
        }

        if (enterpriseName.isEnterpriseAdminExists()) {
            JOptionPane.showMessageDialog(null, "Enterprise admin account already exist, please enter a new one");
            return;
        } 

        if(!WebMedical.checkIfUsernameIsUnique(username)){
            JOptionPane.showMessageDialog(null, "Username is already existing");
            return;
        }
        
        Employee employee = enterpriseName.getEmployeeDirectory().createEmployee(name);

        if (enterpriseName.getEntType().equals(Enterprise.EnterpriseType.DrugCompany)) {
            enterpriseName.getUserAccountDirectory().createEmployeeUserAccount(username, password, employee, new MedsProductionRole());
        } else if (enterpriseName.getEntType().equals(Enterprise.EnterpriseType.FDA)) {
            enterpriseName.getUserAccountDirectory().createEmployeeUserAccount(username, password, employee, new DrugAdminRole());
        } else {
            enterpriseName.getUserAccountDirectory().createEmployeeUserAccount(
                    username, password, employee, new AdminRole());
        }
        
        JOptionPane.showMessageDialog(null, "Enterprise Admin account successfully created");
        populateTable();
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

        upc.remove(this);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.previous(upc);
    }//GEN-LAST:event_backBtnActionPerformed

    private void enterpriseTypeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseTypeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterpriseTypeTxtActionPerformed

    private void enterpriseComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseComboBoxActionPerformed
        Enterprise ent = (Enterprise) enterpriseComboBox.getSelectedItem();

        if (ent != null) {
            enterpriseTypeTxt.setText(ent.getEntType().toString());
        }
    }//GEN-LAST:event_enterpriseComboBoxActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int row = enterpriseTbl.getSelectedRow();

        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row you want to remove");
            return;
        }

        Enterprise enterprise = (Enterprise)enterpriseTbl.getValueAt(row, 0);
        UserAccount userAccount = (UserAccount) enterpriseTbl.getValueAt(row, 3);

        enterprise.getUserAccountDirectory().deleteUserAccount(userAccount);
        JOptionPane.showMessageDialog(null, "User Account deleted");
    }//GEN-LAST:event_deleteBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JComboBox enterpriseComboBox;
    private javax.swing.JTable enterpriseTbl;
    private javax.swing.JTextField enterpriseTypeTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JComboBox networkComboBox;
    private javax.swing.JPasswordField pwdPasswordField;
    private javax.swing.JButton submitJButton;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables
}
