/*

 */
package UserInterface.SystemAdminWorkArea;

import Business.WebMedical;
import Business.Network.Network;
import Business.Util.ProjectUtil;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shail
 */
public class ManageNetworkJPanel extends javax.swing.JPanel {
    
    private JPanel upc;
    private WebMedical webMedical;

    /**
     *
     * Creates new form ManageNetworkJPanel
     */
    public ManageNetworkJPanel(JPanel userProcessContainer, WebMedical system) {
        initComponents();
        
        this.upc = userProcessContainer;
        this.webMedical = system;
        
        populateNetworkTable();
        populateContryCombo();
    }
    
    private void populateContryCombo(){
        countryCombo.removeAllItems();
        
        countryCombo.addItem("INDIA");
        countryCombo.addItem("CHINA");
        countryCombo.addItem("USA");
    }
    
    private void populateNetworkTable() {
        DefaultTableModel dtm = (DefaultTableModel) networkJTable.getModel();
        
        dtm.setRowCount(0);
        for (Network network : webMedical.getNetworkList()) {
            Object[] row = new Object[1];
            row[0] = network.getCountryName();
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        networkJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        submitJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        refreshJButton = new javax.swing.JButton();
        countryCombo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(33, 33, 33));
        setLayout(null);

        networkJTable.setBackground(new java.awt.Color(102, 102, 102));
        networkJTable.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        networkJTable.setForeground(new java.awt.Color(255, 255, 255));
        networkJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name of Network Country"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(networkJTable);
        if (networkJTable.getColumnModel().getColumnCount() > 0) {
            networkJTable.getColumnModel().getColumn(0).setResizable(false);
        }

        add(jScrollPane1);
        jScrollPane1.setBounds(120, 70, 404, 91);

        jLabel1.setFont(new java.awt.Font("Eras Medium ITC", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Country Name");
        add(jLabel1);
        jLabel1.setBounds(58, 257, 180, 28);

        submitJButton.setBackground(new java.awt.Color(51, 51, 51));
        submitJButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        submitJButton.setForeground(new java.awt.Color(255, 255, 255));
        submitJButton.setText("Submit");
        submitJButton.setBorder(null);
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton);
        submitJButton.setBounds(210, 320, 101, 42);

        backJButton.setBackground(new java.awt.Color(51, 51, 51));
        backJButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("Back");
        backJButton.setBorder(null);
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton);
        backJButton.setBounds(60, 320, 77, 42);

        refreshJButton.setBackground(new java.awt.Color(51, 51, 51));
        refreshJButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        refreshJButton.setForeground(new java.awt.Color(255, 255, 255));
        refreshJButton.setText("Refresh");
        refreshJButton.setBorder(null);
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        add(refreshJButton);
        refreshJButton.setBounds(410, 180, 114, 44);

        countryCombo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        countryCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(countryCombo);
        countryCombo.setBounds(280, 260, 140, 25);

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ADD/ MANAGE NETWORK ");
        add(jLabel3);
        jLabel3.setBounds(200, 20, 520, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\shail\\OneDrive\\Desktop\\finalProject indivifual\\world1.png")); // NOI18N
        jLabel5.setText("jLabel5");
        add(jLabel5);
        jLabel5.setBounds(70, 0, 1120, 830);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\shail\\OneDrive\\Desktop\\finalProject indivifual\\grad 123.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 1210, 690);
    }// </editor-fold>//GEN-END:initComponents

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        
        if(countryCombo.getSelectedItem() == null){
            JOptionPane.showMessageDialog(null, "Please select a specific country to add to the network");
            return;
        }
        
        String countryName = (String)countryCombo.getSelectedItem();
        
        if (webMedical.isNetworkExists(countryName)) {
            JOptionPane.showMessageDialog(null, "Network Country already exists");
            return;
        }
        
        Network network = webMedical.createAndAddNetwork();
        network.setCountryName(countryName);
        
        populateNetworkTable();
        JOptionPane.showMessageDialog(null, "Network Country added"
                + " successfully.");
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        upc.remove(this);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.previous(upc);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        populateNetworkTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox countryCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable networkJTable;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
