/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FDARole;

import Business.Drug.Drug;
import Business.Enterprise.Enterprise;
import Business.WebMedical;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FDAApprovalWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nikhil
 */
public class drugAdminWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Enterprise enterprise;
    WebMedical webMedical;
    UserAccount ua;

    public drugAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount ua, Enterprise enterprise,
            WebMedical system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.ua = ua;
        this.webMedical = system;
        populateTable();
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) drugTable.getModel();

        model.setRowCount(0);

        for (WorkRequest wr : enterprise.getWorkQueue().getWorkRequestList()) {

            FDAApprovalWorkRequest approvalRequest = (FDAApprovalWorkRequest) wr;

            Object[] row = new Object[3];
            row[0] = approvalRequest.getDrug();
            row[1] = approvalRequest.getSender();
            row[2] = approvalRequest.getMessage();

            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        drugTable = new javax.swing.JTable();
        medicineInformationBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtMedName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSafetyIssues = new javax.swing.JTextArea();
        respRateJLabel = new javax.swing.JLabel();
        sendApprovalBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(33, 33, 33));
        setLayout(null);

        drugTable.setBackground(new java.awt.Color(51, 51, 51));
        drugTable.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        drugTable.setForeground(new java.awt.Color(255, 255, 255));
        drugTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine Name", "Sender Name", "Message "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(drugTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(78, 174, 510, 91);

        medicineInformationBtn.setBackground(new java.awt.Color(51, 51, 51));
        medicineInformationBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        medicineInformationBtn.setForeground(new java.awt.Color(255, 255, 255));
        medicineInformationBtn.setText("View Medicine's Information");
        medicineInformationBtn.setBorder(null);
        medicineInformationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicineInformationBtnActionPerformed(evt);
            }
        });
        add(medicineInformationBtn);
        medicineInformationBtn.setBounds(78, 283, 206, 41);

        jLabel8.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Medicine Safety Issues");
        add(jLabel8);
        jLabel8.setBounds(80, 470, 190, 24);

        txtMedName.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtMedName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedNameActionPerformed(evt);
            }
        });
        add(txtMedName);
        txtMedName.setBounds(330, 410, 274, 22);

        txtSafetyIssues.setColumns(20);
        txtSafetyIssues.setRows(5);
        jScrollPane2.setViewportView(txtSafetyIssues);

        add(jScrollPane2);
        jScrollPane2.setBounds(330, 460, 274, 68);

        respRateJLabel.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        respRateJLabel.setForeground(new java.awt.Color(255, 255, 255));
        respRateJLabel.setText("Medicine Name");
        add(respRateJLabel);
        respRateJLabel.setBounds(78, 407, 142, 21);

        sendApprovalBtn.setBackground(new java.awt.Color(51, 51, 51));
        sendApprovalBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        sendApprovalBtn.setForeground(new java.awt.Color(255, 255, 255));
        sendApprovalBtn.setText("Approve Medicine");
        sendApprovalBtn.setBorder(null);
        sendApprovalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendApprovalBtnActionPerformed(evt);
            }
        });
        add(sendApprovalBtn);
        sendApprovalBtn.setBounds(450, 280, 139, 41);

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FOOD AND DRUG ADMINISTRATOR  WORK AREA");
        add(jLabel1);
        jLabel1.setBounds(140, 50, 880, 49);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\shail\\OneDrive\\Desktop\\finalProject indivifual\\fda.png")); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(690, 280, 620, 360);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\shail\\OneDrive\\Desktop\\finalProject indivifual\\fda1.png")); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(770, 60, 330, 250);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\shail\\OneDrive\\Desktop\\finalProject indivifual\\Gradient HD 1280x720.jpg")); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(0, 0, 1350, 670);
    }// </editor-fold>//GEN-END:initComponents

    private void medicineInformationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicineInformationBtnActionPerformed
        int row = drugTable.getSelectedRow();

        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }
        
        Drug drug = (Drug) drugTable.getValueAt(row, 0);

        txtMedName.setText(drug.getMedicineName());
        txtSafetyIssues.setText(drug.getSafetyIssues());
    }//GEN-LAST:event_medicineInformationBtnActionPerformed

    private void txtMedNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedNameActionPerformed

    private void sendApprovalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendApprovalBtnActionPerformed
        int row = drugTable.getSelectedRow();

        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }
        
        Drug drug = (Drug) drugTable.getValueAt(row, 0);
        drug.setFdaApproved(true);
        JOptionPane.showMessageDialog(null, "Drug approved");
    }//GEN-LAST:event_sendApprovalBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable drugTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton medicineInformationBtn;
    private javax.swing.JLabel respRateJLabel;
    private javax.swing.JButton sendApprovalBtn;
    private javax.swing.JTextField txtMedName;
    private javax.swing.JTextArea txtSafetyIssues;
    // End of variables declaration//GEN-END:variables
}
