/*
 * 
 */

package UserInterface.DrugCompanyRole;

import Business.Enterprise.Enterprise;
import Business.WebMedical;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Shail
 */
public class MedsCompanyWorkAreaJPanel extends javax.swing.JPanel {

    JPanel upc;
    Enterprise enterprise;
    WebMedical webMedical;
    UserAccount useraccount;
    public MedsCompanyWorkAreaJPanel(JPanel userProcessContainer,UserAccount user, Enterprise enterprise, 
            WebMedical system) {
        initComponents();
        this.upc = userProcessContainer;
        this.enterprise = enterprise;
        this.useraccount = user;
        this.webMedical = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        medsFeedbackBtn = new javax.swing.JButton();
        manageMedsBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(33, 33, 33));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 0, 36)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MEDICINE COMPANY ");
        add(jLabel1);
        jLabel1.setBounds(110, 40, 385, 49);

        medsFeedbackBtn.setBackground(new java.awt.Color(51, 51, 51));
        medsFeedbackBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        medsFeedbackBtn.setForeground(java.awt.Color.white);
        medsFeedbackBtn.setText("Medicines Feedback Information");
        medsFeedbackBtn.setBorder(null);
        medsFeedbackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medsFeedbackBtnActionPerformed(evt);
            }
        });
        add(medsFeedbackBtn);
        medsFeedbackBtn.setBounds(60, 270, 330, 80);

        manageMedsBtn.setBackground(new java.awt.Color(51, 51, 51));
        manageMedsBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        manageMedsBtn.setForeground(new java.awt.Color(255, 255, 255));
        manageMedsBtn.setText("Manage Meds Manufacturing");
        manageMedsBtn.setBorder(null);
        manageMedsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageMedsBtnActionPerformed(evt);
            }
        });
        add(manageMedsBtn);
        manageMedsBtn.setBounds(60, 140, 330, 80);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\shail\\OneDrive\\Desktop\\finalProject indivifual\\med comp.png")); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(420, 20, 520, 400);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\shail\\OneDrive\\Desktop\\finalProject indivifual\\bw grad.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(-330, -390, 1610, 1050);
    }// </editor-fold>//GEN-END:initComponents

    private void medsFeedbackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medsFeedbackBtnActionPerformed

        MedsFeedbackJPanel medsFeedback = new MedsFeedbackJPanel(upc, 
                useraccount, enterprise, webMedical);
        upc.add("DrugFeedbackJPanel", medsFeedback);

        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);

    }//GEN-LAST:event_medsFeedbackBtnActionPerformed

    private void manageMedsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageMedsBtnActionPerformed

        ManageMedsManufacturingJPanel manageMedsManufacturing = new ManageMedsManufacturingJPanel(
                upc, useraccount, enterprise, webMedical);
        upc.add("ManageDrugManufacturingJPanel", manageMedsManufacturing);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_manageMedsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton manageMedsBtn;
    private javax.swing.JButton medsFeedbackBtn;
    // End of variables declaration//GEN-END:variables
}
